---
title: Mill Road Winter Fair.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
cloudinary:
  cloud_name: mill-road-winter-fair
  api_key: 773282259623451
theme: jekyll-theme-architect
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
asset_base: https://www.millroadwinterfair.org/assets/
